import type { InstitutionalContent } from '../institutional.types';

/**
 * Vista institucional (ES). Alertas, casos, inspecciones y cronología de auditoría:
 * no afirma implementación, relación institucional ni cifras reales.
 */
export const institutional: InstitutionalContent = {
  meta: {
    title: 'Vista institucional: alertas, casos e inspección',
    description:
      'Cómo ve una entidad de control las alertas de riesgo, los casos con su cronología, las inspecciones de campo y la cronología de auditoría del piloto fiscal.',
  },

  hero: {
    eyebrow: 'Vista institucional',
    title: 'Riesgos, casos y auditoría en un piloto',
    subtitle:
      'Así ve la información una entidad de control dentro de un piloto de Traza: alertas explicadas en lenguaje claro, casos con su cronología e inspecciones de campo, con permisos por rol.',
  },

  banner: {
    title: 'Vista institucional — solo lectura',
    body:
      'Esta pantalla reúne lo que una entidad de control necesita revisar: alertas, casos, inspecciones y cronología de auditoría, con los permisos de cada rol. Las acciones cambian el estado en esta sesión y no se envían a ningún sistema externo.',
    readOnly: 'Solo lectura: nada de lo que haga aquí se guarda ni se transmite.',
  },

  context: {
    tenantLabel: 'Ámbito',
    tenantValue: 'Piloto de licores · propuesta',
    registryLabel: 'Registro consultado',
    periodLabel: 'Periodo',
    periodValue: 'Últimos 30 días',
  },

  roles: {
    legend: 'Rol de la sesión',
    help: 'Cambie de rol para ver cómo varían la información y las acciones disponibles. La elección solo se conserva mientras la página está abierta.',
    currentLabel: 'Rol activo',
    items: [
      {
        id: 'analyst',
        label: 'Analista',
        description: 'Ve todas las alertas, casos e inspecciones y la cronología completa. Puede reconocer alertas, abrir casos, programar inspecciones y cerrar casos.',
        icon: 'search',
      },
      {
        id: 'inspector',
        label: 'Inspector de campo',
        description: 'Ve solo las alertas y los casos asignados a su persona y únicamente sus propias acciones en la cronología. Puede reconocer alertas y programar inspecciones; no puede abrir ni cerrar casos.',
        icon: 'map-pin',
      },
      {
        id: 'observer',
        label: 'Observador',
        description: 'Permisos limitados: ve el resumen y las listas, pero no el detalle de alertas ni de casos, ni la cronología de auditoría. Puede solicitar acceso.',
        icon: 'eye',
      },
    ],
  },

  viewControls: {
    title: 'Controles de la vista',
    simulateError: 'Probar el estado de error',
    simulateErrorHint: 'Reproduce una respuesta fallida del registro para mostrar el estado de error y el reintento.',
  },

  nav: {
    label: 'Secciones de la vista',
    items: [
      { id: 'resumen', label: 'Resumen' },
      { id: 'alertas', label: 'Alertas' },
      { id: 'casos', label: 'Casos' },
      { id: 'inspecciones', label: 'Inspecciones' },
      { id: 'auditoria', label: 'Auditoría' },
    ],
  },

  summary: {
    id: 'resumen',
    title: 'Resumen del periodo',
    intro: 'Cuatro indicadores del piloto, calculados sobre el período seleccionado.',
    kpis: [
      { key: 'unitsRegistered', label: 'Unidades registradas', hint: 'Identidades emitidas en el registro del piloto.', icon: 'qr' },
      { key: 'verificationsPeriod', label: 'Verificaciones del periodo', hint: 'Consultas públicas realizadas desde un teléfono.', icon: 'scan' },
      { key: 'alertsOpen', label: 'Alertas abiertas', hint: 'Alertas pendientes de reconocimiento.', icon: 'alert' },
      { key: 'casesInProgress', label: 'Casos en curso', hint: 'Casos abiertos o en revisión.', icon: 'document' },
    ],
    byType: {
      title: 'Alertas por tipo',
      intro: 'Cada cuadrado es una alerta del periodo, incluidas las cerradas.',
      countLabel: 'alertas',
    },
  },

  alerts: {
    id: 'alertas',
    title: 'Alertas de riesgo',
    intro:
      'Cada alerta explica qué se detectó, qué confianza aporta y cuál es el siguiente paso. Una firma válida solo indica emisión: las demás señales completan el cuadro.',
    listTitle: 'Lista de alertas',
    countTemplate: '%n alertas',
    filters: { severityLabel: 'Filtrar por severidad', statusLabel: 'Filtrar por estado', all: 'Todas', clear: 'Limpiar filtros' },
    columns: { severity: 'Severidad', type: 'Tipo', unit: 'Unidad', region: 'Región', date: 'Fecha', status: 'Estado' },
    selectPrompt: 'Seleccione una alerta de la lista para ver su explicación, la evidencia y las acciones disponibles.',
    empty: { title: 'No hay alertas con estos filtros', body: 'Pruebe con otra combinación de severidad y estado.', clear: 'Limpiar filtros' },
    detail: {
      title: 'Detalle de la alerta',
      back: 'Volver a la lista',
      unit: 'Unidad',
      product: 'Producto',
      region: 'Región',
      detected: 'Detectada',
      status: 'Estado',
      linkedCase: 'Caso vinculado',
      inspector: 'Inspector asignado',
      explanation: 'Explicación',
      evidence: 'Evidencia: veredicto de la unidad',
      evidenceIntro: 'Resultado de evaluar la unidad con las cuatro señales del motor de verificación.',
      signals: 'Señales',
      actions: 'Acciones',
      actionsIntro: 'Cambian el estado solo en esta página y quedan anotadas en la cronología de auditoría.',
      viewCase: 'Ver caso',
    },
    actions: { acknowledge: 'Reconocer', openCase: 'Abrir caso', scheduleInspection: 'Programar inspección' },
  },

  cases: {
    id: 'casos',
    title: 'Casos',
    intro: 'Un caso agrupa alertas, asigna un inspector y registra cada acción hasta su resultado.',
    listTitle: 'Lista de casos',
    selectPrompt: 'Seleccione un caso para ver su cronología, las alertas vinculadas y el resultado.',
    columns: { id: 'Caso', title: 'Título', status: 'Estado', inspector: 'Inspector', alerts: 'Alertas', opened: 'Abierto' },
    detail: {
      back: 'Volver a la lista',
      status: 'Estado',
      inspector: 'Inspector asignado',
      opened: 'Abierto',
      linkedAlerts: 'Alertas vinculadas',
      timeline: 'Cronología de acciones',
      outcome: 'Resultado',
      actions: 'Acciones',
      closeCase: 'Cerrar caso',
      openAlert: 'Ver alerta',
    },
  },

  inspections: {
    id: 'inspecciones',
    title: 'Inspecciones de campo del piloto',
    intro: 'Visitas programadas o realizadas por los inspectores asignados al piloto.',
    columns: { id: 'Inspección', site: 'Sitio', date: 'Fecha', inspector: 'Inspector', status: 'Estado', result: 'Resultado', caseRef: 'Caso' },
    noResult: 'Pendiente',
  },

  audit: {
    id: 'auditoria',
    title: 'Cronología de auditoría',
    intro: 'Cada acción queda registrada con fecha, actor, rol, objeto y resultado. Las acciones que ejecute se añaden al principio.',
    caption: 'Cronología de auditoría del piloto, de más reciente a más antigua.',
    timezoneNote: 'Horas en UTC.',
    filterLabel: 'Filtrar por rol del actor',
    all: 'Todos',
    inspectorNote: 'Como inspector de campo solo ve sus propias acciones.',
    columns: { at: 'Fecha', actor: 'Actor', role: 'Rol', action: 'Acción', object: 'Objeto', result: 'Resultado' },
    empty: 'No hay entradas para este filtro.',
  },

  permissions: {
    title: 'Sin permisos para esta vista',
    body: 'El rol de observador solo puede ver el resumen. El detalle de alertas y casos y la cronología de auditoría requieren un permiso que en el piloto concede la entidad responsable.',
    audit: 'La cronología de auditoría no está disponible para el rol de observador.',
    request: 'Solicitar acceso',
    requested: 'Solicitud registrada. La revisará la persona administradora del piloto.',
  },

  states: {
    loading: 'Cargando datos…',
    errorTitle: 'No pudimos consultar el registro',
    errorBody: 'El registro respondió con un error. No es un problema de su parte: espere unos segundos y vuelva a intentarlo.',
    retry: 'Reintentar',
    offlineTitle: 'Sin conexión',
    offlineBody: 'Ahora mismo no hay conexión a internet. Puede seguir leyendo esta vista; las acciones se reanudarán cuando la conexión vuelva.',
    onlineTitle: 'Conexión restablecida',
    onlineBody: 'Ya puede continuar.',
  },

  labels: {
    severity: { info: 'Informativa', warning: 'Advertencia', critical: 'Crítica' },
    alertStatus: { open: 'Abierta', acknowledged: 'Reconocida', closed: 'Cerrada' },
    alertType: {
      duplicate_scans: 'Verificaciones repetidas',
      geo_inconsistent: 'Incoherencia geográfica',
      chain_gap: 'Brecha de cadena',
      lot_withdrawn: 'Lote retirado',
      reported: 'Reporte de discrepancia',
      partial_match: 'Coincidencia parcial',
      suspended: 'Registro suspendido',
    },
    caseStatus: { open: 'Abierto', in_review: 'En revisión', closed: 'Cerrado' },
    inspectionStatus: { scheduled: 'Programada', done: 'Realizada' },
    actorRole: { system: 'Sistema', analyst: 'Analista', inspector: 'Inspector', supervisor: 'Supervisión', issuer: 'Emisor', observer: 'Observador' },
    auditAction: {
      alert_created: 'Alerta creada',
      alert_acknowledged: 'Alerta reconocida',
      alert_closed: 'Alerta cerrada',
      case_opened: 'Caso abierto',
      case_note: 'Nota en caso',
      case_closed: 'Caso cerrado',
      inspection_scheduled: 'Inspección programada',
      inspection_completed: 'Inspección realizada',
      lot_revoked: 'Lote revocado',
      report_received: 'Reporte recibido',
      issuer_requested: 'Dictamen solicitado',
      access_requested: 'Acceso solicitado',
      summary_exported: 'Resumen exportado',
    },
    verdict: { valid: 'Ejemplo sin alertas', warning: 'Con advertencias', invalid: 'No válido', unverifiable: 'No verificable' },
    outcome: { pass: 'Correcto', warn: 'Advertencia', fail: 'Falla', skipped: 'No comprobado' },
    checkName: { signature: 'Firma emitida', registry: 'Estado en registro', dataMatch: 'Coincidencia de datos', anomalies: 'Anomalías' },
  },

  island: {
    roles: { analyst: 'Analista', inspector: 'Inspector de campo', observer: 'Observador' },
    sessionActor: 'Sesión · %s',
    live: {
      roleChanged: 'Rol cambiado a %s.',
      filtered: '%n alertas coinciden con los filtros.',
      detailOpened: 'Detalle de la alerta %s abierto.',
      caseOpened: 'Detalle del caso %s abierto.',
      acknowledged: 'Alerta %s reconocida.',
      caseCreated: 'Caso %s abierto y vinculado a la alerta.',
      inspectionScheduled: 'Inspección %s programada.',
      caseClosed: 'Caso %s cerrado.',
      accessRequested: 'Solicitud de acceso registrada.',
      loaded: 'Datos cargados.',
      error: 'Error del registro. Puede reintentar.',
      offline: 'Sin conexión. Las acciones quedan en pausa.',
      online: 'Conexión restablecida.',
    },
    verdictReason: {
      all_checks_passed: 'Resultados favorables; no certifican autenticidad física.',
      anomalies_detected: 'Se detectaron anomalías.',
      data_partial: 'Los datos coinciden solo en parte.',
      registry_suspended: 'El registro está suspendido temporalmente.',
      signature_invalid: 'La firma no corresponde al contenido.',
      signature_malformed: 'La firma está mal formada.',
      not_registered: 'El registro no reconoce el identificador.',
      revoked: 'El identificador fue revocado.',
      data_mismatch: 'Los datos no coinciden.',
      registry_unavailable: 'El registro no está disponible.',
      offline: 'Sin conexión.',
      server_error: 'Error del servidor.',
      timeout: 'Tiempo de espera agotado.',
      unknown_format: 'Formato desconocido.',
    },
    signatureStatus: { valid: 'Firma válida', invalid: 'Firma no válida', malformed: 'Firma mal formada', unknown_key: 'Clave desconocida', not_checked: 'No comprobada' },
    registryStatus: { active: 'Activo', not_found: 'No encontrado', revoked: 'Revocado', suspended: 'Suspendido', unavailable: 'No disponible', not_checked: 'No comprobado' },
    dataMatch: { match: 'Coinciden', partial: 'Coincidencia parcial', mismatch: 'No coinciden', not_checked: 'No comprobada' },
    anomalyCode: {
      duplicate_scans: 'Verificaciones repetidas',
      geo_inconsistent: 'Incoherencia geográfica',
      chain_gap: 'Brecha de cadena',
      lot_withdrawn: 'Lote retirado',
      reported: 'Reporte de discrepancia',
      expired: 'Vencido',
    },
    detail: {
      titleTemplate: '%s · %u',
      caseNone: 'Sin caso vinculado',
      inspectorNone: 'Sin asignar',
      scansTemplate: '%n %v · %r %g · última: %d',
      verificationWord: { one: 'verificación', other: 'verificaciones' },
      regionWord: { one: 'región', other: 'regiones' },
      signalDataMatch: 'Coincidencia de datos',
      signalAnomaly: 'Anomalía',
      signalScans: 'Verificaciones',
      signalNone: 'Sin señales adicionales.',
      keyTemplate: '%a · clave %k',
      registeredTemplate: 'Registrado el %d',
      revokedTemplate: 'Revocado el %d',
      verdictNote: 'Una firma válida solo indica que el identificador fue emitido; no equivale a "auténtico". El veredicto combina las cuatro señales.',
      anomaliesNone: 'Sin anomalías registradas.',
      caseNoOutcome: 'Sin resultado todavía: el caso sigue en curso.',
    },
    hints: {
      acknowledged: 'Alerta reconocida. Puede abrir un caso o programar una inspección.',
      alreadyAcknowledged: 'La alerta ya está reconocida.',
      closed: 'La alerta está cerrada; no admite más acciones.',
      hasCase: 'Ya existe un caso vinculado; use "Ver caso" para seguirlo.',
      needsCase: 'Para programar una inspección primero debe existir un caso vinculado.',
      inspectorCannotOpenCase: 'El rol de inspector no puede abrir casos; lo hace un analista.',
      inspectionExists: 'Ya hay una inspección programada para este caso.',
      caseAlreadyClosed: 'El caso ya está cerrado.',
      inspectorCannotCloseCase: 'El rol de inspector no puede cerrar casos; lo hace un analista o supervisor.',
      offline: 'Sin conexión: la acción no se ejecutó. Vuelva a intentarlo cuando la conexión regrese.',
      observer: 'El rol de observador no puede ejecutar acciones.',
    },
    newCase: {
      titleTemplate: 'Caso abierto desde la alerta %s',
      openedDescription: 'Caso abierto a partir de la alerta %s.',
      closedDescription: 'Caso cerrado desde esta vista.',
      closedOutcome: 'Cerrado desde esta vista. Las alertas vinculadas quedaron cerradas.',
      inspectionDescription: 'Inspección %s programada en %p.',
    },
    audit: {
      acknowledgedResult: 'Reconocida',
      caseOpenedResult: 'Abierto · asignado a R. Salcedo',
      inspectionResult: 'Programada',
      caseClosedResult: 'Cerrado',
      accessResult: 'Registrada',
      acknowledgedDescription: 'Alerta reconocida desde esta vista.',
      caseOpenedDescription: 'Caso abierto a partir de la alerta %s.',
      inspectionDescription: 'Inspección programada en %p.',
      caseClosedDescription: 'Caso cerrado desde esta vista.',
      accessDescription: 'Solicitud de acceso al detalle registrada.',
    },
    access: { requestedTemplate: 'Solicitud registrada: %s' },
  },
};
