import type { InstitutionalContent } from '../institutional.types';

/**
 * Institutional view (EN). Alerts, cases, inspections and audit timeline:
 * it claims no implementation, institutional relationship or real figures.
 */
export const institutional: InstitutionalContent = {
  meta: {
    title: 'Institutional view: alerts, cases and inspections',
    description:
      'How a control entity sees risk alerts, cases with their own timeline, field inspections and the pilot’s full audit trail, with permissions for each role.',
  },

  hero: {
    eyebrow: 'Institutional view',
    title: 'Risks, cases and audit in a pilot',
    subtitle:
      'This is how a control entity sees the information within a Traza pilot: alerts explained in plain language, cases with their timeline and field inspections, with role-based permissions.',
  },

  banner: {
    title: 'Institutional view — read only',
    body:
      'This screen brings together what a control entity needs to review: alerts, cases, inspections and the audit timeline, with each role\'s permissions. Actions change the state of this session and are not sent to any external system.',
    readOnly: 'Read only: nothing you do here is saved or transmitted.',
  },

  context: {
    tenantLabel: 'Scope',
    tenantValue: 'Spirits pilot · proposal',
    registryLabel: 'Registry queried',
    periodLabel: 'Period',
    periodValue: 'Last 30 days',
  },

  roles: {
    legend: 'Session role',
    help: 'Switch roles to see how the information and the available actions change. The choice is only kept while the page is open.',
    currentLabel: 'Active role',
    items: [
      {
        id: 'analyst',
        label: 'Analyst',
        description: 'Sees every alert, case and inspection and the full timeline. Can acknowledge alerts, open cases, schedule inspections and close cases.',
        icon: 'search',
      },
      {
        id: 'inspector',
        label: 'Field inspector',
        description: 'Sees only the alerts and cases assigned to them and only their own actions in the timeline. Can acknowledge alerts and schedule inspections; cannot open or close cases.',
        icon: 'map-pin',
      },
      {
        id: 'observer',
        label: 'Observer',
        description: 'Limited permissions: sees the summary and the lists, but not alert or case details nor the audit timeline. Can request access.',
        icon: 'eye',
      },
    ],
  },

  viewControls: {
    title: 'View controls',
    simulateError: 'Test the error state',
    simulateErrorHint: 'Reproduces a failed registry response to show the error state and the retry.',
  },

  nav: {
    label: 'Sections of this view',
    items: [
      { id: 'summary', label: 'Summary' },
      { id: 'alerts', label: 'Alerts' },
      { id: 'cases', label: 'Cases' },
      { id: 'inspections', label: 'Inspections' },
      { id: 'audit', label: 'Audit' },
    ],
  },

  summary: {
    id: 'summary',
    title: 'Period summary',
    intro: 'Four indicators for the pilot, computed over the selected period.',
    kpis: [
      { key: 'unitsRegistered', label: 'Units registered', hint: 'Identities issued in the pilot registry.', icon: 'qr' },
      { key: 'verificationsPeriod', label: 'Verifications this period', hint: 'Public checks made from a phone.', icon: 'scan' },
      { key: 'alertsOpen', label: 'Open alerts', hint: 'Alerts awaiting acknowledgement.', icon: 'alert' },
      { key: 'casesInProgress', label: 'Cases in progress', hint: 'Cases open or under review.', icon: 'document' },
    ],
    byType: {
      title: 'Alerts by type',
      intro: 'Each square is one alert in the period, closed ones included.',
      countLabel: 'alerts',
    },
  },

  alerts: {
    id: 'alerts',
    title: 'Risk alerts',
    intro:
      'Each alert explains what was detected, how much confidence it gives and what the next step is. A valid signature only means the identifier was issued: the other signals complete the picture.',
    listTitle: 'Alert list',
    countTemplate: '%n alerts',
    filters: { severityLabel: 'Filter by severity', statusLabel: 'Filter by status', all: 'All', clear: 'Clear filters' },
    columns: { severity: 'Severity', type: 'Type', unit: 'Unit', region: 'Region', date: 'Date', status: 'Status' },
    selectPrompt: 'Select an alert from the list to see its explanation, the evidence and the available actions.',
    empty: { title: 'No alerts match these filters', body: 'Try another combination of severity and status.', clear: 'Clear filters' },
    detail: {
      title: 'Alert detail',
      back: 'Back to the list',
      unit: 'Unit',
      product: 'Product',
      region: 'Region',
      detected: 'Detected',
      status: 'Status',
      linkedCase: 'Linked case',
      inspector: 'Assigned inspector',
      explanation: 'Explanation',
      evidence: 'Evidence: verdict for the unit',
      evidenceIntro: 'Result of evaluating the unit with the four signals of the verification engine.',
      signals: 'Signals',
      actions: 'Actions',
      actionsIntro: 'They change the state only on this page and are recorded in the audit timeline.',
      viewCase: 'View case',
    },
    actions: { acknowledge: 'Acknowledge', openCase: 'Open case', scheduleInspection: 'Schedule inspection' },
  },

  cases: {
    id: 'cases',
    title: 'Cases',
    intro: 'A case groups alerts, assigns an inspector and records every action up to its outcome.',
    listTitle: 'Case list',
    selectPrompt: 'Select a case to see its timeline, the linked alerts and the outcome.',
    columns: { id: 'Case', title: 'Title', status: 'Status', inspector: 'Inspector', alerts: 'Alerts', opened: 'Opened' },
    detail: {
      back: 'Back to the list',
      status: 'Status',
      inspector: 'Assigned inspector',
      opened: 'Opened',
      linkedAlerts: 'Linked alerts',
      timeline: 'Action timeline',
      outcome: 'Outcome',
      actions: 'Actions',
      closeCase: 'Close case',
      openAlert: 'View alert',
    },
  },

  inspections: {
    id: 'inspections',
    title: 'Pilot field inspections',
    intro: 'Visits scheduled or completed by the inspectors assigned to the pilot.',
    columns: { id: 'Inspection', site: 'Site', date: 'Date', inspector: 'Inspector', status: 'Status', result: 'Result', caseRef: 'Case' },
    noResult: 'Pending',
  },

  audit: {
    id: 'audit',
    title: 'Audit timeline',
    intro: 'Every action is recorded with date, actor, role, object and result. Actions you run are added at the top.',
    caption: 'Pilot audit timeline, newest first.',
    timezoneNote: 'Times in UTC.',
    filterLabel: 'Filter by actor role',
    all: 'All',
    inspectorNote: 'As a field inspector you only see your own actions.',
    columns: { at: 'Date', actor: 'Actor', role: 'Role', action: 'Action', object: 'Object', result: 'Result' },
    empty: 'No entries for this filter.',
  },

  permissions: {
    title: 'No permission for this view',
    body: 'The observer role can only see the summary. Alert and case details and the audit timeline require a permission that, in the pilot, the responsible entity grants.',
    audit: 'The audit timeline is not available to the observer role.',
    request: 'Request access',
    requested: 'Request recorded. The pilot administrator will review it.',
  },

  states: {
    loading: 'Loading data…',
    errorTitle: 'We could not query the registry',
    errorBody: 'The registry responded with an error. It is not a problem on your side: wait a few seconds and try again.',
    retry: 'Retry',
    offlineTitle: 'Offline',
    offlineBody: 'There is no internet connection right now. You can keep reading this view; actions will resume when the connection returns.',
    onlineTitle: 'Connection restored',
    onlineBody: 'You can continue.',
  },

  labels: {
    severity: { info: 'Info', warning: 'Warning', critical: 'Critical' },
    alertStatus: { open: 'Open', acknowledged: 'Acknowledged', closed: 'Closed' },
    alertType: {
      duplicate_scans: 'Repeated verifications',
      geo_inconsistent: 'Geographic inconsistency',
      pending_activation: 'Pending activation',
      lot_withdrawn: 'Lot withdrawn',
      reported: 'Discrepancy report',
      partial_match: 'Partial match',
      suspended: 'Registry suspended',
    },
    caseStatus: { open: 'Open', in_review: 'Under review', closed: 'Closed' },
    inspectionStatus: { scheduled: 'Scheduled', done: 'Completed' },
    actorRole: { system: 'System', analyst: 'Analyst', inspector: 'Inspector', supervisor: 'Supervision', issuer: 'Issuer', observer: 'Observer' },
    auditAction: {
      alert_created: 'Alert created',
      alert_acknowledged: 'Alert acknowledged',
      alert_closed: 'Alert closed',
      case_opened: 'Case opened',
      case_note: 'Case note',
      case_closed: 'Case closed',
      inspection_scheduled: 'Inspection scheduled',
      inspection_completed: 'Inspection completed',
      lot_revoked: 'Lot revoked',
      report_received: 'Report received',
      issuer_requested: 'Statement requested',
      access_requested: 'Access requested',
      summary_exported: 'Summary exported',
    },
    verdict: { valid: 'Example without alerts', warning: 'With warnings', invalid: 'Invalid', unverifiable: 'Unverifiable' },
    outcome: { pass: 'OK', warn: 'Warning', fail: 'Failed', skipped: 'Not checked' },
    checkName: { signature: 'Signature issued', registry: 'Registry status', dataMatch: 'Data match', anomalies: 'Anomalies' },
  },

  island: {
    roles: { analyst: 'Analyst', inspector: 'Field inspector', observer: 'Observer' },
    sessionActor: 'Session · %s',
    live: {
      roleChanged: 'Role changed to %s.',
      filtered: '%n alerts match the filters.',
      detailOpened: 'Alert %s detail opened.',
      caseOpened: 'Case %s detail opened.',
      acknowledged: 'Alert %s acknowledged.',
      caseCreated: 'Case %s opened and linked to the alert.',
      inspectionScheduled: 'Inspection %s scheduled.',
      caseClosed: 'Case %s closed.',
      accessRequested: 'Access request recorded.',
      loaded: 'Data loaded.',
      error: 'Registry error. You can retry.',
      offline: 'Offline. Actions are paused.',
      online: 'Connection restored.',
    },
    verdictReason: {
      all_checks_passed: 'Favourable results; they do not certify physical authenticity.',
      anomalies_detected: 'Anomalies were detected.',
      data_partial: 'The data only partially match.',
      registry_suspended: 'The registry entry is temporarily suspended.',
      signature_invalid: 'The signature does not match the contents.',
      signature_malformed: 'The signature is malformed.',
      not_registered: 'The registry does not recognise the identifier.',
      revoked: 'The identifier was revoked.',
      data_mismatch: 'The data do not match.',
      registry_unavailable: 'The registry is unavailable.',
      offline: 'Offline.',
      server_error: 'Server error.',
      timeout: 'Timed out.',
      unknown_format: 'Unknown format.',
    },
    signatureStatus: { valid: 'Valid signature', invalid: 'Invalid signature', malformed: 'Malformed signature', unknown_key: 'Unknown key', not_checked: 'Not checked' },
    registryStatus: { active: 'Active', not_found: 'Not found', revoked: 'Revoked', suspended: 'Suspended', unavailable: 'Unavailable', not_checked: 'Not checked' },
    dataMatch: { match: 'Match', partial: 'Partial match', mismatch: 'Mismatch', not_checked: 'Not checked' },
    anomalyCode: {
      duplicate_scans: 'Repeated verifications',
      geo_inconsistent: 'Geographic inconsistency',
      chain_gap: 'Chain gap',
      lot_withdrawn: 'Lot withdrawn',
      reported: 'Discrepancy report',
      expired: 'Expired',
    },
    detail: {
      titleTemplate: '%s · %u',
      caseNone: 'No linked case',
      inspectorNone: 'Unassigned',
      scansTemplate: '%n %v · %r %g · last: %d',
      verificationWord: { one: 'verification', other: 'verifications' },
      regionWord: { one: 'region', other: 'regions' },
      signalDataMatch: 'Data match',
      signalAnomaly: 'Anomaly',
      signalScans: 'Verifications',
      signalNone: 'No additional signals.',
      keyTemplate: '%a · key %k',
      registeredTemplate: 'Registered on %d',
      revokedTemplate: 'Revoked on %d',
      verdictNote: 'A valid signature only means the identifier was issued; it is not the same as "authentic". The verdict combines the four signals.',
      anomaliesNone: 'No anomalies recorded.',
      caseNoOutcome: 'No outcome yet: the case is still in progress.',
    },
    hints: {
      acknowledged: 'Alert acknowledged. You can open a case or schedule an inspection.',
      alreadyAcknowledged: 'The alert is already acknowledged.',
      closed: 'The alert is closed; no further actions are available.',
      hasCase: 'A linked case already exists; use "View case" to follow it.',
      needsCase: 'To schedule an inspection a linked case must exist first.',
      inspectorCannotOpenCase: 'The inspector role cannot open cases; an analyst does.',
      inspectionExists: 'An inspection is already scheduled for this case.',
      caseAlreadyClosed: 'The case is already closed.',
      inspectorCannotCloseCase: 'The inspector role cannot close cases; an analyst or supervisor does.',
      offline: 'Offline: the action did not run. Try again when the connection returns.',
      observer: 'The observer role cannot run actions.',
    },
    newCase: {
      titleTemplate: 'Case opened from alert %s',
      openedDescription: 'Case opened based on alert %s.',
      closedDescription: 'Case closed from this view.',
      closedOutcome: 'Closed from this view. Linked alerts were closed.',
      inspectionDescription: 'Inspection %s scheduled at %p.',
    },
    audit: {
      acknowledgedResult: 'Acknowledged',
      caseOpenedResult: 'Opened · assigned to R. Salcedo',
      inspectionResult: 'Scheduled',
      caseClosedResult: 'Closed',
      accessResult: 'Recorded',
      acknowledgedDescription: 'Alert acknowledged from this view.',
      caseOpenedDescription: 'Case opened based on alert %s.',
      inspectionDescription: 'Inspection scheduled at %p.',
      caseClosedDescription: 'Case closed from this view.',
      accessDescription: 'Request for access to the detail recorded.',
    },
    access: { requestedTemplate: 'Request recorded: %s' },
  },
};
