#!/usr/bin/env python3
"""Generate the example print-sequence Code 128 and reuse the site's public QR.

Development-only dependency: zxing-cpp (Python). No barcode library is shipped
with the site. Usage: python scripts/stamp-codes.py [--check]
The six-digit print sequence is illustrative, distinct from the unit identifier.
This is plain Code 128, not a GS1 application identifier or a fiscal mark.
Source API: https://github.com/zxing-cpp/zxing-cpp/tree/master/wrappers/python
"""
from pathlib import Path
import argparse
import json
import xml.etree.ElementTree as ET
import zxingcpp

ROOT = Path(__file__).resolve().parents[1]
SEQUENCE = '000001'


def render():
    barcode = zxingcpp.create_barcode(SEQUENCE, zxingcpp.BarcodeFormat.Code128)
    svg = ET.fromstring(zxingcpp.write_barcode_to_svg(barcode, add_hrt=False, add_quiet_zones=True))
    path = svg.find('.//{http://www.w3.org/2000/svg}path')
    assert path is not None
    # Independently decode the generated symbol before saving the browser data.
    decoded = zxingcpp.read_barcode(zxingcpp.write_barcode_to_image(barcode, scale=3))
    assert decoded is not None and decoded.text == SEQUENCE
    data = {'value': SEQUENCE, 'format': 'Code 128', 'width': int(svg.attrib['width']),
            'height': int(svg.attrib['height']), 'quietZoneModules': 10, 'path': path.attrib['d']}
    return '''/** Generated by scripts/stamp-codes.py. Functional symbols, not decorative artwork. */
import { FEATURED_UNIT_CODE } from '@/fixtures/units';
import { HERO_QR_PATH, HERO_QR_SIZE, HERO_QR_URL } from './hero-qr';

export const EXAMPLE_UNIT_ID = FEATURED_UNIT_CODE;
/** URL and four-module quiet zone shared with the public hero QR. */
export const UNIT_QR_URL = HERO_QR_URL;
export const UNIT_QR_PATH = HERO_QR_PATH;
export const UNIT_QR_SIZE = HERO_QR_SIZE;
/** Example print sequence; plain Code 128, unrelated to GS1 or fiscal validation. */
export const STAMP_PRINT_BARCODE = ''' + json.dumps(data, indent=2) + ''' as const;
'''


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'src/brand/unit-qr.ts'
    generated = render()
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('Stamp barcode data is stale; run scripts/stamp-codes.py')
        print('Code 128 data matches the generator; decode verified: ' + SEQUENCE)
    else:
        target.write_text(generated)
        print('Generated ' + str(target.relative_to(ROOT)))
