/** Generated by scripts/stamp-codes.py. Functional symbols, not decorative artwork. */
import { FEATURED_UNIT_CODE } from '@/fixtures/units';
import { HERO_QR_PATH, HERO_QR_SIZE, HERO_QR_URL } from './hero-qr';

export const EXAMPLE_UNIT_ID = FEATURED_UNIT_CODE;
/** URL and four-module quiet zone shared with the public hero QR. */
export const UNIT_QR_URL = HERO_QR_URL;
export const UNIT_QR_PATH = HERO_QR_PATH;
export const UNIT_QR_SIZE = HERO_QR_SIZE;
/** Example print sequence; plain Code 128, unrelated to GS1 or fiscal validation. */
export const STAMP_PRINT_BARCODE = {
  "value": "000001",
  "format": "Code 128",
  "width": 88,
  "height": 50,
  "quietZoneModules": 10,
  "path": "M10 0h2v50h-2ZM13 0h1v50h-1ZM16 0h3v50h-3ZM21 0h2v50h-2ZM24 0h2v50h-2ZM28 0h2v50h-2ZM32 0h2v50h-2ZM35 0h2v50h-2ZM39 0h2v50h-2ZM43 0h2v50h-2ZM47 0h2v50h-2ZM50 0h2v50h-2ZM54 0h1v50h-1ZM58 0h1v50h-1ZM61 0h2v50h-2ZM65 0h2v50h-2ZM70 0h3v50h-3ZM74 0h1v50h-1ZM76 0h2v50h-2Z"
} as const;
